# Logitech Attack3
axis_linear_x: 1  # Forward/Back
scale_linear_x: 0.7
linear_turbo_multiplier: 1.5

axis_angular_yaw: 0  # Left/Right
scale_angular_yaw: 0.4

enable_button: 0  # Trigger
enable_turbo_button: 1  # Button 2 aka thumb button
