# Logitech Extreme 3D Pro
is_3D: true

axis_linear: 1  # Forward/Back [X]
scale_linear: 0.7
scale_linear_turbo: 1.5

axis_horizontal: 0  # Left/Right [Y]
scale_horizontal: 0.7
scale_horizontal_turbo: 1.5

axis_vertical: 3  # Throttle [Z]
scale_vertical: 0.7
scale_vertical_turbo: 1.5

axis_angular: 2  # Twist
scale_angular: 0.4

enable_button: 0  # Trigger
enable_turbo_button: 1  # Button 2 aka thumb button
