# Logitech Extreme 3D Pro
is_3D: true
axis_linear_x: 1  # Forward/Back [X]
scale_linear_x: 0.7

axis_linear_y: 0  # Left/Right [Y]
scale_linear_y: 0.7

axis_linear_z: 3  # Throttle [Z]
scale_linear_z: 0.7

linear_turbo_multiplier: 2.0

axis_angular_yaw: 2  # Twist
scale_angular_yaw: 0.4

enable_button: 0  # Trigger
enable_turbo_button: 1  # Button 2 aka thumb button
